Adicionar no seu conf 
....
<integration>
  <name>custom-teams</name>
  <level>3</level>
  <hook_url>htps://-----SUA-WEBHOOK-AQUI----</hook_url>
  <alert_format>json</alert_format>
</integration>
....
.....
 <wodle name="docker-listener">
      <interval>10m</interval>
      <attempts>5</attempts>
      <run_on_start>no</run_on_start>
      <disabled>no</disabled>
  </wodle>
....


